# Generated by Django 3.2.5 on 2021-07-04 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setting_text', models.CharField(max_length=200)),
                ('choice', models.IntegerField(default=0)),
            ],
        ),
    ]
