# Generated by Django 3.2.5 on 2021-07-04 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playerinterface', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='choice',
        ),
        migrations.AddField(
            model_name='settings',
            name='fadeout_text',
            field=models.CharField(default='Fade out', max_length=200),
        ),
        migrations.AddField(
            model_name='settings',
            name='fadeout_time_choice',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='settings',
            name='fadeout_toggle',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='settings',
            name='fadeout_value_choice',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='settings',
            name='loop_text',
            field=models.CharField(default='Loop sound', max_length=200),
        ),
        migrations.AddField(
            model_name='settings',
            name='loop_toggle',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='sound_choice',
            field=models.CharField(blank=True, choices=[('test1', 'test1.txt'), ('test2', 'test2.txt')], default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='sound_text',
            field=models.CharField(default='Sound to play', max_length=200),
        ),
        migrations.AddField(
            model_name='settings',
            name='timer_choice',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='settings',
            name='timer_text',
            field=models.CharField(default='Cutoff timer', max_length=200),
        ),
        migrations.AddField(
            model_name='settings',
            name='timer_toggle',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='settings',
            name='volume_choice',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='settings',
            name='volume_text',
            field=models.CharField(default='Volume', max_length=200),
        ),
        migrations.AlterField(
            model_name='settings',
            name='setting_text',
            field=models.CharField(default='Raspberry Pi audio player settings', max_length=200, verbose_name='Raspberry Pi audio player settings'),
        ),
    ]
