# Generated by Django 3.2.5 on 2021-07-05 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playerinterface', '0002_auto_20210704_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='sound_choice',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
