# Generated by Django 3.2.5 on 2021-07-06 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playerinterface', '0004_auto_20210705_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='loop_text',
            field=models.CharField(default='Loop song', max_length=200),
        ),
        migrations.AlterField(
            model_name='settings',
            name='play_text',
            field=models.CharField(default='Play song', max_length=200),
        ),
        migrations.AlterField(
            model_name='settings',
            name='sound_text',
            field=models.CharField(default='Select song to play', max_length=200),
        ),
        migrations.AlterField(
            model_name='settings',
            name='stop_text',
            field=models.CharField(default='Stop song', max_length=200),
        ),
    ]
