# Generated by Django 3.2.5 on 2021-07-13 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playerinterface', '0006_auto_20210709_1611'),
    ]

    operations = [
        migrations.RenameField(
            model_name='settings',
            old_name='shuffle_toggle',
            new_name='random_toggle',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='shuffle_text',
        ),
        migrations.AddField(
            model_name='settings',
            name='random_text',
            field=models.CharField(default='random songs', max_length=200),
        ),
        migrations.AlterField(
            model_name='settings',
            name='setting_text',
            field=models.CharField(default='Audio player settings', max_length=200, verbose_name='Audio player settings'),
        ),
    ]
