# Generated by Django 3.2.5 on 2021-07-13 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playerinterface', '0007_auto_20210713_2126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='settings',
            old_name='sound_choice',
            new_name='song_choice',
        ),
        migrations.RenameField(
            model_name='settings',
            old_name='sound_text',
            new_name='song_text',
        ),
    ]
